package com.wut.car.model;

import java.io.Serializable;

/**
 * Middleman 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Middleman implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** name. */
	private String name;

	/** bianhao. */
	private String bianhao;

	/** sex. */
	private Integer sex;

	/** gongling. */
	private Integer gongling;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Middleman() {
	}

	/**
	 * name 傪愝掕偟傑偡.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * name 傪庢摼偟傑偡.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * bianhao 傪愝掕偟傑偡.
	 * 
	 * @param bianhao
	 *            bianhao
	 */
	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	/**
	 * bianhao 傪庢摼偟傑偡.
	 * 
	 * @return bianhao
	 */
	public String getBianhao() {
		return this.bianhao;
	}

	/**
	 * sex 傪愝掕偟傑偡.
	 * 
	 * @param sex
	 *            sex
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * sex 傪庢摼偟傑偡.
	 * 
	 * @return sex
	 */
	public Integer getSex() {
		return this.sex;
	}

	/**
	 * gongling 傪愝掕偟傑偡.
	 * 
	 * @param gongling
	 *            gongling
	 */
	public void setGongling(Integer gongling) {
		this.gongling = gongling;
	}

	/**
	 * gongling 傪庢摼偟傑偡.
	 * 
	 * @return gongling
	 */
	public Integer getGongling() {
		return this.gongling;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Middleman other = (Middleman) obj;
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}

		return true;
	}

}
